require "scott.options"
require "scott.keymaps"
require "scott.plugins"
require "scott.colorscheme"
require "scott.cmp"
require "scott.lsp"
require "scott.treesitter"
require "scott.autopairs"
require "scott.comment"
require "scott.gitsigns"
require "scott.bufferline"
require "scott.nvim-tree"
require "scott.telescope"
require "scott.lualine"
require "scott.indentline"
require "scott.whichkey"
--[[ require "scott.toggleterm" ]]
